python3 main.py \
    --domain $1 \
    --problem $2 \
    --train_samples 20 \
    --val_samples 5 \
    --test_samples 5 \
    --img_h 48 \
    --img_w 48 \
    --backbone resnet18 \
    --max_epochs $3 \
    --devices 1 \
    --accelerator gpu \
    --precision 16 \
    --optimizer sgd \
    --scheduler warmup_cosine \
    --lr 0.3 \
    --classifier_lr 0.3 \
    --weight_decay 1e-4 \
    --batch_size $4 \
    --num_workers 4 \
    --name mocov2plus-$1-$2-$3-$4 \
    --project solo-learn \
    --wandb \
    --method mocov2plus \
    --proj_hidden_dim 2048 \
    --queue_size $4 \
    --temperature 0.2 \
    --base_tau_momentum 0.99 \
    --final_tau_momentum 0.999 \
    --momentum_classifier \
    --save_checkpoint
