./scripts/barlow.sh grid grid1 5
./scripts/byol.sh grid grid1 5
./scripts/deepclusterv2.sh grid grid1 5
./scripts/mocov2plus.sh grid grid1 5
./scripts/nnbyol.sh grid grid1 5
./scripts/nnsiam.sh grid grid1 5
./scripts/ressl.sh grid grid1 5
./scripts/simclr.sh grid grid1 5
./scripts/simsiam.sh grid grid1 5
./scripts/supcon.sh grid grid1 5
./scripts/swav.sh grid grid1 5
./scripts/barlow.sh grid grid1 10
./scripts/byol.sh grid grid1 10
./scripts/deepclusterv2.sh grid grid1 10
./scripts/mocov2plus.sh grid grid1 10
./scripts/nnbyol.sh grid grid1 10
./scripts/nnsiam.sh grid grid1 10
./scripts/ressl.sh grid grid1 10
./scripts/simclr.sh grid grid1 10
./scripts/simsiam.sh grid grid1 10
./scripts/supcon.sh grid grid1 10
./scripts/swav.sh grid grid1 10